plugins {
    id 'com.gradleup.nmcp.settings' version '1.6.1'
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

nmcpSettings {
    centralPortal {
        username = providers.gradleProperty('mavenCentralUsername')
        password = providers.gradleProperty('mavenCentralPassword')
        publishingType = 'AUTOMATIC'
    }
}

rootProject.name = 'lint-rules'

include 'dependencies'
include 'pmd-rules'
include 'codenarc-rules'
