plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation 'com.diffplug.spotless:spotless-plugin-gradle:8.9.0'
    implementation 'net.ltgt.gradle:gradle-errorprone-plugin:5.1.0'
    implementation 'net.ltgt.gradle:gradle-nullaway-plugin:3.1.0'
    implementation 'io.github.sgtsilvio.gradle:gradle-metadata:0.7.0'
    implementation 'info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.19.0'
    implementation 'io.github.joke.conventional-version:io.github.joke.conventional-version.gradle.plugin:2.1.0'
}
