plugins {
    id 'java'
    id 'maven-publish'
    id 'conventions'
}

dependencies {
    annotationProcessor platform(project(':dependencies'))
    annotationProcessor 'io.github.joke.jspecify:processor'
    annotationProcessor 'org.projectlombok:lombok'

    pmd project(':rules')

    compileOnly platform(project(':dependencies'))
    compileOnly 'net.sourceforge.pmd:pmd-core'
    compileOnly 'net.sourceforge.pmd:pmd-java'
    compileOnly 'org.jetbrains:annotations'
    compileOnly 'org.jspecify:jspecify'
    compileOnly 'org.projectlombok:lombok'

    testImplementation platform(project(':dependencies'))
    testImplementation 'net.sourceforge.pmd:pmd-core'
    testImplementation 'net.sourceforge.pmd:pmd-java'
    testImplementation 'net.sourceforge.pmd:pmd-test'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testImplementation 'org.mockito:mockito-core'

    testCompileOnly 'org.jetbrains:annotations'

    testRuntimeOnly platform(project(':dependencies'))
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'

}
